on:
  push:
    branches:
      - main

name: Refresh latest tag

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Select node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Refresh 'latest' tag
        run: |
          git tag -d latest || true
          git push origin :latest || true
          git tag latest
          git push origin latest
