on:
  push:
    branches:
      - main
    paths-ignore:
      - 'dist/**'

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Package
        run: |
          yarn install
          yarn test
          yarn build
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push origin HEAD:main
      - name: Refresh 'latest' tag
        run: |
          git tag -d latest || true
          git push origin :latest || true
          git tag latest
          git push origin latest
